/**
 * All flavor text pools, organized by phase and context.
 */
const Flavor = (function() {

  const phase1 = [
    "The hold music is a midi rendition of something that was never a song.",
    "A recorded voice assures you that you are valued. It does not sound convinced.",
    "\"Your estimated wait time is... [long pause] ...thank you for holding.\"",
    "A brief silence. You wonder if someone picked up. They did not.",
    "The hold music loops. You recognize the seam now. You always will.",
    "\"Did you know? Our offices are closed during solar eclipses.\"",
    "You hear a click. Your heart leaps. It was nothing.",
    "\"All representatives are assisting callers who are also on hold.\"",
    "The hold music just sampled itself.",
    "You've memorized the hold music. You hate that you've memorized it.",
    "A fly lands on you. It stays. You are that still.",
    "The recorded voice mispronounces your name. It's the most human thing today.",
    "You've forgotten why you called. This doesn't seem important anymore.",
    "\"We are experiencing higher than normal call volume.\" Since 1997.",
    "The phone cord has become load-bearing.",
    "The hold music fades out. You lean forward. It fades back in. Of course.",
    "You wonder if the hold music was composed or if it simply appeared one day, fully formed, in a server rack.",
    "\"For English, press 1.\" You already pressed 1. You pressed it forty minutes ago.",
    "The hold music has a key change. You feel nothing.",
    "You begin to suspect the hold music is procedurally generated by an algorithm that has never experienced joy.",
    "A second voice joins the first. They are not harmonizing. They are not aware of each other.",
    "\"Your call may be monitored for quality assurance.\" You wonder whose quality. You wonder whose assurance.",
    "The hold music transitions seamlessly into a different song that sounds exactly the same.",
    "You can no longer remember what silence sounds like.",
    "The recorded voice returns. It says nothing new. It never does.",
    "\"Please stay on the line. A representative will be with you...\" The sentence does not end.",
    "You've been holding so long the phone has warmed to body temperature. It is part of you now.",
    "The hold music skips. For one glorious moment, you thought it was over.",
    "You realize you've been nodding along to the hold music. You stop. You start again.",
    "Someone in the background coughs. A human. They do not pick up.",
    "\"Thank you for your patience.\" You have not given it willingly.",
    "The hold music has no bass. You find this personally offensive.",
    "You try to hum along. You can't. The melody resists memorization on purpose.",
    "A different recorded voice appears. It says the same things with different inflection. Progress.",
    "The phone makes a sound like it's about to connect. It doesn't. It never was going to.",
  ];

  const phase2 = [
    "You have been transferred to the Dept. of Alarm Clock Calibration.",
    "\"Please continue to hold. Your patience is being monitored for quality assurance.\"",
    "You notice the wallpaper pattern for the first time. You've lived here nine years.",
    "A spider has built a web between you and the phone cradle. You respect its ambition.",
    "You try to remember what the sun looks like. You get close but not quite.",
    "The hold music changes key. This is the most exciting thing in twenty minutes.",
    "\"Your call may be recorded for training purposes.\" Whose training? For what?",
    "The hold music has developed a subtle crackle. It's aging. Like you.",
    "You've been transferred to someone's voicemail. The voicemail is also on hold.",
    "A new menu appears. None of the options apply. You press 0. Nothing happens.",
    "\"We value your loyalty.\" You are not loyal. You are trapped.",
    "The phone's battery icon blinks. You feel a kinship with it.",
    "You consider hanging up. The thought fills you with an emotion you can't name.",
    "\"Your queue position has not changed.\" You didn't ask.",
    "Someone picks up. \"Wrong department.\" Click. You're back in the queue.",
    "The automated system asks you to rate your experience so far. There is no option below 1.",
    "\"For billing, press 3. For existential dread, remain on the line.\"",
    "You hear typing in the background. Someone is there. They are ignoring you specifically.",
    "The hold music briefly becomes just... breathing. Then it returns to normal.",
    "\"Did you know you can manage your account online?\" You cannot. You've tried.",
    "The system plays an ad for the company you're already calling. Bold.",
    "You've been on hold long enough that the phone company has sent you a loyalty reward. It's more hold time.",
    "A child answers. \"Mommy's busy.\" Click. Redialed automatically. Somehow.",
    "The hold music plays a chord that doesn't resolve. It will never resolve.",
    "\"An agent will be with you in approximately...\" Silence. Infinite silence.",
  ];

  const phase3 = [
    "You are becoming a geological event.",
    "Future civilizations will study your sediment layers.",
    "The dust has opinions now. They're mostly about you.",
    "The dust mites have developed agriculture on your left shoulder.",
    "You are less a person and more a landscape feature at this point.",
    "A layer of dust has settled on the dust. Archaeology is now possible.",
    "Someone placed a 'do not disturb' sign on you. You are furniture now.",
    "The building has been condemned around you. You remain on hold.",
    "Termites have inspected you and moved on. Too dusty.",
    "The dust on your phone has formed a protective crust. Nature is healing.",
    "A small ecosystem has developed in the dust on your knee. You are a biome.",
    "Geologists have named the layer of dust on your left arm. It's called the Holdocene.",
    "The dust has reached a depth where it has its own weather patterns.",
    "You have been carbon-dated. The results are 'distressing.'",
    "A documentary crew has set up nearby. They are filming your sediment layers in time-lapse.",
    "The dust remembers things you've forgotten. It whispers them sometimes.",
    "Archaeologists have found a fossilized tear in your lower dust strata. They've dated it to 'early frustration.'",
    "The phone is now a fossil. You are holding a fossil to your ear. The fossil is still on hold.",
    "Your dust layers contain a complete record of the hold music. Future scientists will be confused.",
    "A stalagmite has begun forming between you and the floor. You admire its commitment.",
    "The dust has stratified into distinct geological eras: Pre-Hold, Early Hold, Late Hold, and Whatever This Is.",
    "Birds have begun nesting in your upper dust layers. You wish them well.",
    "You have been declared a protected natural landmark. Construction cannot occur within 50 feet of you.",
    "The dust is warm. You are warm. Everything is warm and still and ancient.",
    "Houston, we have dust.",
    "The Oort Cloud is 40% particulate matter.",
    "First contact. They're also on hold.",
    "There is nothing left that isn't dust. Except the hold music.",
  ];

  const hangup = [
    "You hang up. You stare at the wall. The wall does not stare back. It's a wall.",
    "Your will to live hit zero. You set the phone down with the gentleness of a man defeated.",
    "Connection lost. Was it you, or them? It was you. It's always you.",
    "You've been disconnected from Meridian Solutions Inc. They will not miss you.",
    "You hung up. The silence is deafening. Also worse than the hold music.",
  ];

  function random(pool) {
    return pool[Math.floor(Math.random() * pool.length)];
  }

  function getForPhase(phase) {
    if (phase === 1) return random(phase1);
    if (phase === 2) return random(phase2);
    return random(phase3);
  }

  function getHangup() {
    return random(hangup);
  }

  return { phase1, phase2, phase3, hangup, random, getForPhase, getHangup };
})();
