/**
 * Flavor text pools - dry, absurd humor that escalates with time.
 * Split into acts for Phase 1, plus milestone-specific lines.
 */
const Flavor = (function() {

  // Act 1: 0-30 min active. Fresh confusion. Still has hope.
  const act1 = [
    'The hold music is a saxophone solo that has been going for eleven minutes.',
    'You begin to suspect the hold music is procedurally generated by an algorithm that has never experienced joy.',
    'A recorded voice assures you that your call is important. You are skeptical.',
    'The system plays an ad for the company you\'re already calling. Bold.',
    'You wonder if the representative is real or if this is all a simulation.',
    'The hold music transitions seamlessly into what might be a different song. Or the same song. You can\'t tell.',
    'Your chair is getting warm. You haven\'t moved.',
    'A fly lands on your phone. It stays. It has nowhere better to be either.',
    'The hold music has a key change. You feel nothing.',
    'You count the ceiling tiles. There are seventeen. You count again. Still seventeen.',
    'The recording mentions "your approximate wait time" but never actually says what it is.',
    'Someone in the background of the hold recording coughs. Is that live? Was it ever?',
    'You wonder what the people behind you in the queue are doing. Are they also staring at a wall?',
    'The hold music fades out. Silence. Your heart races. Then it fades back in. False alarm.',
    'You notice the phone cord has wrapped around your wrist. When did that happen?',
    'A crackle on the line. Static. Hope surges and dies in 0.3 seconds.',
    'The recorded voice mentions "valued customers." You feel neither valued nor like a customer.',
    'You start humming along to the hold music. You stop yourself. You start again.',
    'The fluorescent light above you buzzes at the same frequency as the hold music. Coincidence.',
    'You read the same line of text on the wall three times without comprehending it.',
  ];

  // Act 2: 30-60 min active. Resignation setting in. Drier.
  const act2 = [
    'You have memorized the hold music. All four bars of it.',
    'The concept of "soon" has lost all meaning.',
    'You wonder if the representative has a family. If they go home at night. If they exist.',
    'The dust on your arm has formed a thin but definitive layer. You name it.',
    'You calculate that you have now heard the hold music loop 847 times. Give or take.',
    'A new recorded message plays. It says the same thing as the last one, but with slightly different inflection.',
    'Your coffee is cold. It has been cold for a geological age.',
    'The hold music develops a slight crackle. You find it comforting. This concerns you.',
    'You have developed opinions about the saxophone solo. Strong ones.',
    'The phone has become an extension of your body. You no longer feel where you end and it begins.',
    'You try to remember what you were calling about. Something about money. Probably.',
    'The recorded voice thanks you for your patience. This is the funniest thing you have ever heard.',
    'A spider has built a web between your elbow and the desk. You respect its commitment.',
    'The hold music changes key again. You feel this deeply and are ashamed.',
    'You realize you have been holding your breath. For how long? Unknown.',
    'Your reflection in the phone screen looks older than you remember.',
    'The system mentions "quality assurance." You wonder whose quality. Whose assurance.',
    'You have forgotten the sound of human speech that isn\'t recorded.',
    'The dust is getting thicker. It\'s not unpleasant. Just... inevitable.',
    'You wonder if this is what astronauts feel like. Alone. Floating. Waiting.',
    'The hold music has become the soundtrack of your existence. You no longer hear it. It hears you.',
    'A notification on your phone. From a different life. You ignore it.',
    'You begin to suspect that the queue number is decorative.',
  ];

  // Act 3: 60+ min active. Existential. The mundane has become cosmic.
  const act3 = [
    'Time has become a suggestion rather than a rule.',
    'You have forgotten what silence sounds like. The hold music is silence now.',
    'The dust has opinions about you. They are neutral. This is the dust\'s highest compliment.',
    'You wonder if the call center exists in the same dimension as you. Evidence is inconclusive.',
    'The hold music has started to sound like a prophecy.',
    'You are no longer waiting. You are existing in a state of permanent pre-answer.',
    'The concept of "hanging up" occurs to you like a half-remembered dream. Impossible. Absurd.',
    'You and the hold music have reached a detente. Neither will yield. Neither can.',
    'The representative you\'re waiting for hasn\'t been born yet. You suspect this.',
    'Your queue position is a philosophical statement about the nature of progress.',
    'The dust is writing something. You can almost read it. Almost.',
    'You have become the hold music. The hold music has become you. There is no difference.',
    'A distant memory: sunshine. The outdoors. Was that real? Were you real then?',
    'The $1.47 has become a concept rather than an amount. Like "infinity" or "justice."',
    'You suspect the saxophone player is also on hold somewhere. Playing to pass the time.',
    'The phone is warm. Not from your hand. From something else. Something patient.',
    'Time passes. Or you pass through time. The distinction has collapsed.',
    'The hold music skips. For a moment you see the code underneath reality. Then it resumes.',
    'You have been here long enough that the building has started to grow around you.',
    'The queue advances. Or does it? Maybe you\'re the one moving backward.',
    'The dust remembers when you arrived. The dust remembers everything.',
    'You could hang up. The thought is hilarious. Hang up and do what? Exist without purpose?',
    'The recorded voice apologizes again. The apology has worn grooves in reality.',
  ];

  // After department transfer
  const transfer = [
    'The new hold music is somehow worse. You didn\'t think that was possible.',
    '"Specialist Department." The word "specialist" has never felt less reassuring.',
    'You wonder if the Specialist Department is a real place or a concept designed to break you.',
    'The new hold music is the old hold music, but transposed down a half step. Criminal.',
    'Transferred. The word echoes. Were you ever anywhere at all?',
    'The Specialist Department hold music sounds like it was composed by someone who\'s also on hold.',
  ];

  // During time freeze
  const frozen = [
    'The clock has stopped. You are the only thing moving in the universe.',
    'Each step forward costs everything. Each step forward is everything.',
    'Time waits for you now. Not the other way around.',
    'The queue is all that remains. The queue is all that matters.',
    'Forward. Always forward. There is nothing else.',
    'You move. Time follows. Obediently. Finally.',
  ];

  // Hangup recovery
  const hangup = [
    'The line goes dead. The universe doesn\'t care.',
    'Disconnected. The silence is deafening.',
    'You hung up. Or they hung up. Or the concept of connection simply gave out.',
    'The phone emits a tone. A flatline. A eulogy.',
    'Connection lost. But was there ever a connection to lose?',
    'The call ends. Not with a bang. With a click.',
    'Dial tone. The saddest sound in the world.',
    'They hung up on you. After all that. After everything.',
  ];

  function getForPhase(phase) {
    if (phase !== 1) return act1[Math.floor(Math.random() * act1.length)];
    return getPhase1();
  }

  function getPhase1() {
    // Check game state for context
    const state = Game.state;
    if (state.flags.timeFrozen) {
      return frozen[Math.floor(Math.random() * frozen.length)];
    }
    if (state.flags.departmentTransferred && Math.random() < 0.3) {
      return transfer[Math.floor(Math.random() * transfer.length)];
    }
    const activeMin = state.activePlayTime / 60;
    if (activeMin >= 60) return act3[Math.floor(Math.random() * act3.length)];
    if (activeMin >= 30) return act2[Math.floor(Math.random() * act2.length)];
    return act1[Math.floor(Math.random() * act1.length)];
  }

  function getHangup() {
    return hangup[Math.floor(Math.random() * hangup.length)];
  }

  return { getForPhase, getHangup, phase1: act1 };
})();
